### ISSUE TITLE
I am not able to use Jath for the following xml

### ISSUE THREAD

**Issue by rhka** [dnewcome/jath#12]
```
<list>
<item>example1</item>
<item>example2</item>
<item>example3</item>
<item>example4</item>
</list>
```

When am executing the following scripts, it returns only one value. Anyone can help ?

Jath.parse(["//list",{
            name : 'item'
        }],data);

**Comment by dnewcome** [comment]
You will need to use collection template syntax over the item tag.

Try something like this.

```
Jath.parse(["//item",{
   name : '.'
}],data);
```

**Comment by rhka** [comment]
Thanks a lot. It's working fine now.
