### ISSUE TITLE
Need the help to parse n-level nested xml

### ISSUE THREAD

**Issue by sijuthankachan** [dnewcome/jath#22]
hi i need to parse the following xlm.. its an n-level xml(children tag will go to n level)
how can i parse this using jath parser

![sample](https://cloud.githubusercontent.com/assets/1881015/3746101/51ae8dca-17b9-11e4-876c-0e951dedea0a.PNG)

i need the following json object

![sampleout](https://cloud.githubusercontent.com/assets/1881015/3746222/1d216c46-17bc-11e4-826d-754914becc47.PNG)

**Comment by dnewcome** [comment]
Hi sijuthankachan, take a look at the following issue for a solution:
https://github.com/dnewcome/jath/issues/4
