### ISSUE TITLE
Support for recursively nested structures

### ISSUE THREAD

**Issue by masto** [dnewcome/jath#4]
I may be missing it but there doesn't seem to be a way to deal with XML like:

``` xml
<item name="foo">
  <status code="1" />
  <item name="bar">
    <status code="2" />
  </item>
  <item name="baz">
    <status code="3" />
    <item name="biff">
       <status code="4" />
    </item>
  </item>
</item>
```

(In the case where there can be an arbitrary level of nesting).

This could be turned into e.g.:

``` json
{
  items: [
    {
      name: "foo",
      status: 1,
      items: [
      {
        name: "bar",
        status: 2
      },
      {
        name: "baz",
        status: 3,
        items: [
          {
            name: "biff",
            status: 4
          }
        ]
      }
    }
  }
}
```

Or even...

``` json
[
  foo: {
    status: 1,
    bar: {
      status: 2
    },
    baz: {
      status: 3,
      biff: {
        status: 4
      }
    }
  }
]
```

It seems like being able to refer to a named key elsewhere in the template might make the first translation possible.

**Comment by dnewcome** [comment]
Thanks for bringing this issue up. I'm taking a look at this right now. Doing something like this should give you the result that you want, but it isn't doesn't make for the nicest template syntax:

``` javascript
var template = [ 'item', { name: '@name', status: 'status/@code' } ];
template[1].items = template;
```

You can't create a recursive data structure directly in a JS definition but you can create a cycle after the fact as I showed above.

It might be nice to implement an escape code like we do for literals. For example using '+template' to refer to a recursive template:

``` javascript
var template = [ 'item', { name: '@name', status: 'status/@code', items: '+template' } ];
```

Let me know what you think.

(BTW I'm adding some test cases for this, to be checked in probably later tonight hopefully)

**Comment by masto** [comment]
Cool, I didn't realize there was a workaround.  I do much prefer the latter, though, and that's basically what I thinking.  Wouldn't it be `'+item'`, though?  It seems like you'd want to be able to refer to a specific key within the template in order to have some flexibility about exactly what's nested where.  For example, `<item>` may not be the top-level node, but rather a recursive part of some larger structure, so you can't recursively include template, just the `item` piece.  If this isn't making sense, I can try to concoct a better example...
